global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "envoy-stats"
    metrics_path: /stats/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["envoy:8082"]
        labels:
          group: "services"
