# a very minimal declarative config file
_format_version: "1.1"
_transform: true

services:
- name: httpbin
  host: "httpbin"
  path: "/"
  port: 8080
  protocol: http
  routes:
  - name: httpbin
    methods:
    - GET
    paths:
    - /
    - /anything
    - /uuid
  plugins:
  - name: proxy-wasm
    config:
      filters:
      - name: main
        config: '{
           "rules": [
              "Include @demo-conf",
              "Include @crs-setup-demo-conf",
              "SecRuleEngine DetectionOnly",
              "SecDebugLogLevel 3",
              "Include @owasp_crs/*.conf",
              "SecRule REQUEST_URI \"@streq /uuid\" \"id:101,phase:1,t:lowercase,deny\"",
              "SecRule REQUEST_BODY \"@rx maliciouspayload\" \"id:102,phase:2,t:lowercase,deny\"",
              "SecRule RESPONSE_HEADERS::status \"@rx 406\" \"id:103,phase:3,t:lowercase,deny\"",
              "SecRule RESPONSE_BODY \"@contains responsebodycode\" \"id:104,phase:4,t:lowercase,deny\""
            ]
        }'