{
 "title": "Example dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "description": "Current amount of allocated memory in bytes. Total of both new and old Envoy processes on hot restart.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "envoy_server_memory_allocated", "legendFormat": "Envoy" }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "description": "Current reserved heap size. New Envoy process heap size on hot restart.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "envoy_server_memory_heap_size", "legendFormat": "Envoy" }
   ]
  },
  {
   "title": "Max Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(envoy_server_memory_allocated[$__range])"
    }
   ]
  },
  {
   "title": "Max Heap Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(envoy_server_memory_heap_size[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}