services:
  httpbin:
    image: kennethreitz/httpbin:latest
  envoy:
    depends_on:
      - httpbin
    image: envoyproxy/envoy:v1.23-latest
    command:
      - -c
      - /conf/envoy-config.yaml
    volumes:
      - ../build:/build
      - ../example:/conf  # relying on envoy-config file from /example/
  tests:
    depends_on:
      - envoy
    build:
      context: .
      dockerfile: ./Dockerfile.curl
