name: Build TinyGo
on:
  push:
    branches:
      - main
    paths:
      - buildtools/tinygo/**
      - .github/workflows/buildtools-tinygo.yaml
  pull_request:
    branches:
      - main
    paths:
      - buildtools/tinygo/**
      - .github/workflows/buildtools-tinygo.yaml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/buildtools-tinygo
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      - uses: docker/build-push-action@v3
        with:
          context: buildtools/tinygo
          file: buildtools/tinygo/wasi-libc.Dockerfile
          push: true
          platforms: linux/amd64
          tags: localhost:5000/buildtools-tinygo-wasi-libc:main

      - uses: docker/build-push-action@v3
        with:
          context: buildtools/tinygo
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          build-args: WASI_LIBC_IMAGE=localhost:5000/buildtools-tinygo-wasi-libc:main
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
