name: Build TinyGo
on:
  push:
    branches:
      - main
    paths:
      - buildtools/tinygo/**
      - .github/workflows/buildtools-tinygo.yaml
  pull_request:
    branches:
      - main
    paths:
      - buildtools/tinygo/**
      - .github/workflows/buildtools-tinygo.yaml

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/buildtools-tinygo

      - uses: docker/build-push-action@v3
        with:
          context: buildtools/tinygo
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
